from logging import error
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import pearsonr, kendalltau, spearmanr

## Selection of the dataset
InOrOut = "OutLoop"
#InOrOut = "InLoop"
shiftRange = 6
 
## Loading Files 
camFit = np.load("data/"+InOrOut+"/CameraFit.npy")
camProj = np.load("data/"+InOrOut+"/CameraProj.npy")
OL_phs = np.load("data/"+InOrOut+"/OL_Phase.npy")
OL_amp = np.load("data/"+InOrOut+"/OL_Magnitude.npy")
ILmOL_phs = np.load("data/"+InOrOut+"/OL_Phase.npy") - np.load("data/"+InOrOut+"/IL_Phase.npy")
ILmOL_amp = np.load("data/"+InOrOut+"/OL_Magnitude.npy") - np.load("data/"+InOrOut+"/IL_Magnitude.npy")
laser_Phs = np.load("data/"+InOrOut+"/Laser_Phs.npy")   
laser_amp = np.load("data/"+InOrOut+"/Laser_Amp.npy")  

#Shifting step by step 
data_ln = len(camFit)
OL_phs_shift = np.zeros([data_ln,shiftRange])
OL_amp_shift = np.zeros([data_ln,shiftRange])
ILmOL_phs_shift = np.zeros([data_ln,shiftRange])
ILmOL_amp_shift = np.zeros([data_ln,shiftRange])
laser_Phs_shift = np.zeros([data_ln,shiftRange])
laser_amp_shift = np.zeros([data_ln,shiftRange])
for j in range(shiftRange):
    OL_phs_shift[:,j] = np.roll(OL_phs,-(j+1))
    OL_amp_shift[:,j] = np.roll(OL_amp,-(j+1))
    ILmOL_phs_shift[:,j] = np.roll(ILmOL_phs,-(j+1))
    ILmOL_amp_shift[:,j] = np.roll(ILmOL_amp,-(j+1))
    laser_Phs_shift[:,j] = np.roll(laser_Phs,-(j+1))
    laser_amp_shift[:,j] = np.roll(laser_amp,-(j+1))

#Correlations Pearsonr 
cP_OLphs,_= pearsonr(OL_phs,camFit)
cP_OLamp,_= pearsonr(OL_amp,camFit)
cP_ILmOL_phs,_= pearsonr(ILmOL_phs,camFit)
cP_ILmOL_amp,_= pearsonr(ILmOL_amp,camFit)
cP_Lasphs,_= pearsonr(laser_Phs,camFit)
cP_Lasamp,_= pearsonr(laser_amp,camFit)
cP_OLphs_shif = np.zeros(shiftRange)
cP_OLamp_shif = np.zeros(shiftRange)
cP_ILmOL_phs_shif = np.zeros(shiftRange)
cP_ILmOL_amp_shif = np.zeros(shiftRange)
cP_Lasphs_shif = np.zeros(shiftRange)
cP_Lasamp_shif = np.zeros(shiftRange) 
for i in range(shiftRange):
    j = i+1
    cP_OLphs_shif[i],_= pearsonr(OL_phs_shift[:-j,i],camFit[:-j])
    cP_OLamp_shif[i],_= pearsonr(OL_amp_shift[:-j,i],camFit[:-j])
    cP_ILmOL_phs_shif[i],_ = pearsonr(ILmOL_phs_shift[:-j,i],camFit[:-j])
    cP_ILmOL_amp_shif[i],_ = pearsonr(ILmOL_amp_shift[:-j,i],camFit[:-j])
    cP_Lasphs_shif[i],_= pearsonr(laser_Phs_shift[:-j,i],camFit[:-j])
    cP_Lasamp_shif[i],_= pearsonr(laser_amp_shift[:-j,i],camFit[:-j])

#Correlations Kendalltau 
cK_OLphs,_= kendalltau(OL_phs,camFit)
cK_OLamp,_= kendalltau(OL_amp,camFit)
cK_ILmOL_phs,_= kendalltau(ILmOL_phs,camFit)
cK_ILmOL_amp,_= kendalltau(ILmOL_amp,camFit)
cK_Lasphs,_= kendalltau(laser_Phs,camFit)
cK_Lasamp,_= kendalltau(laser_amp,camFit)
cK_OLphs_shif = np.zeros(shiftRange)
cK_OLamp_shif = np.zeros(shiftRange)
cK_ILmOL_phs_shif = np.zeros(shiftRange)
cK_ILmOL_amp_shif = np.zeros(shiftRange)
cK_Lasphs_shif = np.zeros(shiftRange)
cK_Lasamp_shif = np.zeros(shiftRange) 
for i in range(shiftRange):
    j = i+1
    cK_OLphs_shif[i],_= kendalltau(OL_phs_shift[:-j,i],camFit[:-j])
    cK_OLamp_shif[i],_= kendalltau(OL_amp_shift[:-j,i],camFit[:-j])
    cK_ILmOL_phs_shif[i],_ = kendalltau(ILmOL_phs_shift[:-j,i],camFit[:-j])
    cK_ILmOL_amp_shif[i],_ = kendalltau(ILmOL_amp_shift[:-j,i],camFit[:-j])
    cK_Lasphs_shif[i],_= kendalltau(laser_Phs_shift[:-j,i],camFit[:-j])
    cK_Lasamp_shif[i],_= kendalltau(laser_amp_shift[:-j,i],camFit[:-j])

#Correlations Spearmanr 
cS_OLphs,_= spearmanr(OL_phs,camFit)
cS_OLamp,_= spearmanr(OL_amp,camFit)
cS_ILmOL_phs,_= spearmanr(ILmOL_phs,camFit)
cS_ILmOL_amp,_= spearmanr(ILmOL_amp,camFit)
cS_Lasphs,_= spearmanr(laser_Phs,camFit)
cS_Lasamp,_= spearmanr(laser_amp,camFit)
cS_OLphs_shif = np.zeros(shiftRange)
cS_OLamp_shif = np.zeros(shiftRange)
cS_ILmOL_phs_shif = np.zeros(shiftRange)
cS_ILmOL_amp_shif = np.zeros(shiftRange)
cS_Lasphs_shif = np.zeros(shiftRange)
cS_Lasamp_shif = np.zeros(shiftRange) 
for i in range(shiftRange):
    j = i+1
    cS_OLphs_shif[i],_= spearmanr(OL_phs_shift[:-j,i],camFit[:-j])
    cS_OLamp_shif[i],_= spearmanr(OL_amp_shift[:-j,i],camFit[:-j])
    cS_ILmOL_phs_shif[i],_ = spearmanr(ILmOL_phs_shift[:-j,i],camFit[:-j])
    cS_ILmOL_amp_shif[i],_ = spearmanr(ILmOL_amp_shift[:-j,i],camFit[:-j])
    cS_Lasphs_shif[i],_= spearmanr(laser_Phs_shift[:-j,i],camFit[:-j])
    cS_Lasamp_shif[i],_= spearmanr(laser_amp_shift[:-j,i],camFit[:-j])

#Plotting 
fig, ax = plt.subplots(shiftRange+1,6,figsize=(14,7),sharey=True,sharex='col')
ax[0,0].plot(OL_phs,camFit, color="#e63946", marker="+", linestyle="", label='Pearsonr: %.3f \n Kendalltau: %.3f \n Spearmanr: %.3f' %(cP_OLphs, cK_OLphs, cS_OLphs)) 
ax[0,0].ticklabel_format(axis="y", style="sci", scilimits=(0,0))
ax[0,1].ticklabel_format(axis="x", style="sci", scilimits=(0,0))
ax[0,0].set_ylabel("Y [CameraFit]")
ax[shiftRange,0].set_xlabel("X1 [RF Phs]")
#ax[shiftRange,0].set_xticks([])
ax[0,0].legend(fontsize = 7)
ax[0,1].plot(OL_amp,camFit, color="#a8dadc", marker="+", linestyle="", label='Pearsonr: %.3f \n Kendalltau: %.3f \n Spearmanr: %.3f' %(cP_OLamp, cK_OLamp, cS_OLamp)) 
ax[0,1].ticklabel_format(axis="y", style="sci", scilimits=(0,0))
ax[0,1].ticklabel_format(axis="x", style="sci", scilimits=(0,0))
ax[shiftRange,1].set_xlabel("X2 [RF Amp]")
#ax[shiftRange,1].set_xticks([])
ax[0,1].legend(fontsize = 7)
ax[0,2].plot(laser_Phs,camFit, color="#457b9d", marker="+", linestyle="", label='Pearsonr: %.3f \n Kendalltau: %.3f \n Spearmanr: %.3f' %(cP_Lasphs, cK_Lasphs, cS_Lasphs)) 
ax[0,2].ticklabel_format(axis="y", style="sci", scilimits=(0,0))
ax[0,2].ticklabel_format(axis="x", style="sci", scilimits=(0,0))
ax[shiftRange,2].set_xlabel("X1 [Laser Phs]")
#ax[shiftRange,2].set_xticks([])
ax[0,2].legend(fontsize = 7)
ax[0,3].plot(laser_amp,camFit, color="#1d3557", marker="+", linestyle="", label='Pearsonr: %.3f \n Kendalltau: %.3f \n Spearmanr: %.3f' %(cP_Lasamp, cK_Lasamp, cS_Lasamp)) 
ax[0,3].ticklabel_format(axis="y", style="sci", scilimits=(0,0))
ax[0,3].ticklabel_format(axis="x", style="sci", scilimits=(0,0))
ax[shiftRange,3].set_xlabel("X1 [Laser Amp]")
#ax[shiftRange,3].set_xticks([])
ax[0,3].legend(fontsize = 7)
ax[0,4].plot(ILmOL_phs,camFit, color="#7b2cbf", marker="+", linestyle="", label='Pearsonr: %.3f \n Kendalltau: %.3f \n Spearmanr: %.3f' %(cP_ILmOL_phs, cK_ILmOL_phs, cS_ILmOL_phs)) 
ax[0,4].ticklabel_format(axis="y", style="sci", scilimits=(0,0))
ax[0,4].ticklabel_format(axis="x", style="sci", scilimits=(0,0))
ax[shiftRange,4].set_xlabel("X1 [InLoop-OutLoop Phs]")
#ax[shiftRange,4].set_xticks([])
ax[0,4].legend(fontsize = 7)
ax[0,5].plot(ILmOL_amp,camFit, color="#fb8500", marker="+", linestyle="", label='Pearsonr: %.3f \n Kendalltau: %.3f \n Spearmanr: %.3f' %(cP_ILmOL_amp, cK_ILmOL_amp, cS_ILmOL_amp)) 
ax[0,5].ticklabel_format(axis="y", style="sci", scilimits=(0,0))
ax[0,5].ticklabel_format(axis="x", style="sci", scilimits=(0,0))
ax[shiftRange,5].set_xlabel("X1 [InLoop-OutLoop Amp]")
#ax[shiftRange,5].set_xticks([])
ax[0,5].legend(fontsize = 7)
ax1 = ax[0,5].twinx()
ax1.set_ylabel('Y[t] vs X[t]',fontsize = 8)
ax1.set_yticks([])
for i in range(shiftRange):
    j = i+1
    ax[j,0].plot(OL_phs_shift[:-j,i],camFit[:-j], color="#e63946", marker="+", linestyle="", label='Pearsonr: %.3f \n Kendalltau: %.3f \n Spearmanr: %.3f' %(cP_OLphs_shif[i], cK_OLphs_shif[i], cS_OLphs_shif[i]))
    ax[j,0].ticklabel_format(axis="y", style="sci", scilimits=(0,0))
    ax[j,0].ticklabel_format(axis="x", style="sci", scilimits=(0,0))
    ax[j,0].set_ylabel("Y [CameraFit]")
    ax[j,0].legend(fontsize = 7)
    ax[j,1].plot(OL_amp_shift[:-j,i],camFit[:-j], color="#a8dadc", marker="+", linestyle="",  label='Pearsonr: %.3f \n Kendalltau: %.3f \n Spearmanr: %.3f' %(cP_OLamp_shif[i], cK_OLamp_shif[i], cS_OLamp_shif[i]))
    ax[j,1].ticklabel_format(axis="y", style="sci", scilimits=(0,0))
    ax[j,1].ticklabel_format(axis="x", style="sci", scilimits=(0,0))
    ax[j,1].legend(fontsize = 7)
    ax[j,2].plot(laser_Phs_shift[:-j,i],camFit[:-j], color="#457b9d", marker="+", linestyle="", label='Pearsonr: %.3f \n Kendalltau: %.3f \n Spearmanr: %.3f' %(cP_Lasphs_shif[i], cK_Lasphs_shif[i], cS_Lasphs_shif[i]))
    ax[j,2].ticklabel_format(axis="y", style="sci", scilimits=(0,0))
    ax[j,2].ticklabel_format(axis="x", style="sci", scilimits=(0,0))
    ax[j,2].legend(fontsize = 7)
    ax[j,3].plot(laser_amp_shift[:-j,i],camFit[:-j], color="#1d3557", marker="+", linestyle="", label='Pearsonr: %.3f \n Kendalltau %.3f \n Spearmanr %.3f' %(cP_Lasamp_shif[i], cK_Lasamp_shif[i], cS_Lasamp_shif[i]))
    ax[j,3].ticklabel_format(axis="y", style="sci", scilimits=(0,0))
    ax[j,3].ticklabel_format(axis="x", style="sci", scilimits=(0,0))
    ax[j,3].legend(fontsize = 7)
    ax[j,4].plot(ILmOL_phs_shift[:-j,i],camFit[:-j], color="#7b2cbf", marker="+", linestyle="", label='Pearsonr: %.3f \n Kendalltau: %.3f \n Spearmanr: %.3f' %(cP_ILmOL_phs_shif[i], cK_ILmOL_phs_shif[i], cS_ILmOL_phs_shif[i]))
    ax[j,4].ticklabel_format(axis="y", style="sci", scilimits=(0,0))
    ax[j,4].ticklabel_format(axis="x", style="sci", scilimits=(0,0))
    ax[j,4].legend(fontsize = 7)
    ax[j,5].plot(ILmOL_amp_shift[:-j,i],camFit[:-j], color="#fb8500", marker="+", linestyle="", label='Pearsonr: %.3f \n Kendalltau %.3f \n Spearmanr %.3f' %(cP_ILmOL_amp_shif[i], cK_ILmOL_amp_shif[i], cS_ILmOL_amp_shif[i]))
    ax[j,5].ticklabel_format(axis="y", style="sci", scilimits=(0,0))
    ax[j,5].ticklabel_format(axis="x", style="sci", scilimits=(0,0))
    ax[j,5].legend(fontsize = 7)
    ax1 = ax[j,5].twinx()
    ax1.set_ylabel('Y[t] vs X[t+%.0f]'%(j), fontsize = 8)
    ax1.set_yticks([])
# plt.show()

#Shifting step by step 
camFit_shift = np.zeros([data_ln,shiftRange])
for j in range(shiftRange):
    camFit_shift[:,j] = np.roll(camFit,-(j+1))
#Correlations 
cP_camFit_shift = np.zeros(shiftRange) 
cK_camFit_shift = np.zeros(shiftRange) 
cS_camFit_shift = np.zeros(shiftRange) 
for i in range(shiftRange):
    j = i+1
    cP_camFit_shift[i],_= pearsonr(camFit_shift[:-j,i],camFit[:-j])
    cK_camFit_shift[i],_= kendalltau(camFit_shift[:-j,i],camFit[:-j])
    cS_camFit_shift[i],_= spearmanr(camFit_shift[:-j,i],camFit[:-j])
colori = ["#f72585","#b5179e","#7209b7","#560bad","#480ca8","#3a0ca3","#3f37c9","#4895ef","#4895ef","#168aad","#52b69a","#99d98c"]
if (shiftRange>len(colori)):
    error("ADD MORE COLOR CODE FOR THE PLOT")
fig, ax = plt.subplots(1,shiftRange,figsize=(14,4),sharey=True)
plt.subplots_adjust(right = 0.99, left = 0.065, wspace = 0)
for i in range(shiftRange):
    j = i+1
    ax[i].plot(camFit_shift[:-j,i],camFit[:-j], color=colori[i], marker="+", linestyle="", label="Pearsonr: %.3f \n Kendalltau: %.3f \n Spearmanr:  %.3f" %(cP_camFit_shift[i], cK_camFit_shift[i], cS_camFit_shift[i]))
    ax[i].ticklabel_format(axis="y", style="sci", scilimits=(0,0))
    ax[i].ticklabel_format(axis="x", style="sci", scilimits=(0,0))
    ax[i].legend(fontsize = 7)
    ax[i].set_xlabel('Y[t+%.0f]'%(j))
ax[0].set_ylabel("Y[t]")
# plt.show()

camFit_Norm = (camFit-np.min(camFit))/(np.max(camFit)-np.min(camFit))
OL_phs_Norm = (OL_phs-np.min(OL_phs))/(np.max(OL_phs)-np.min(OL_phs))
OL_amp_Norm = (OL_amp-np.min(OL_amp))/(np.max(OL_amp)-np.min(OL_amp))
laser_amp_Norm = (laser_amp-np.min(laser_amp))/(np.max(laser_amp)-np.min(laser_amp))
fig, ax = plt.subplots(4,figsize=(14,7), sharex=True)
plt.subplots_adjust(right = 0.99, left = 0.065, hspace = 0)
ax[0].plot(camFit_Norm, color="r", marker="", linestyle="-", label='Y') 
ax[0].set_ylabel('Y[t]')
ax[0].grid()
ax[1].plot(OL_phs_Norm, color="b", marker="", linestyle="-", label='RF Phs') 
ax[1].set_ylabel('RF Phs')
ax[1].grid()
ax[2].plot(OL_amp_Norm, color="m", marker="", linestyle="-", label='RF Amp') 
ax[2].set_ylabel('RF Amp')
ax[2].grid()
ax[3].plot(laser_amp_Norm, color="k", marker="", linestyle="-", label='Laser Amp') 
ax[3].set_ylabel('Laser Amp')
ax[3].grid()
ax[3].set_xlabel('Time')
plt.show()